manifest = "f45113920bb63f51d08dabbf2a0ae8ed197843e8b3995c763946f525d8a70fa9"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.24.0" ]
revision = "37278170bcbe6e22f6eebed0d33d5df4e0d015e1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.24.0" ]
revision = "f4baf718b1370779f5a4b7e64d640d20061f91e0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.24.0" ]
revision = "d67c3fcac36b11bdb19664af223b7c8874d83964"
