manifest = "b95e0005dd5cf56fc2e4c81fe651b49baaae699bc45be365d9120acde0d47b38"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.0" ]
revision = "65a8650af82725f556021c523cb3a87f6b93c268"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.0" ]
revision = "ed1ffa5577a8de8ac7b894194acccd59b184ce3d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.0" ]
revision = "2e69574def6115cae8f5bfd5fbdcbe6d0da009cd"
