manifest = "ac5387ad85cec101f8f6a16a729a9360a79842beef532ea033b57cc1e73378bd"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.62.0" ]
revision = "21f3b72527d1b03930640c1e25d57e86447fcaa4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.62.0" ]
revision = "7ae3be7b21333ca15b32eefe62b65ee6b3e328b5"
