manifest = "0f72bcbdf09711a9c8fc79c7609597a021eb237e071f29ac07d5abf452563948"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.48.0" ]
revision = "f2a3d12da550aca457374033ba38554ccb3b06df"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.48.0" ]
revision = "5c7e908149e4b2609294c1b1d88bbdf97b5438a6"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.48.0" ]
revision = "7b719723d288114d7e90613502793221442805e3"
