manifest = "3364442957086790564e2bc70401dc2875c78d07069556d91d5bd9c91f4316df"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.41.0" ]
revision = "c32805df725494aca225f78f2d64b24bdf99e56a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.41.0" ]
revision = "7d302ba51a8553f5465676c7bdde1099e468b37d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.41.0" ]
revision = "16ff33bdc884b911234f0e4526d541ae0a87f812"
