manifest = "607dc32f88587627747cfb2f50749793d29951e2fd5bff7eec0756fba040e3c3"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[lock]]
name = "github.com/buckaroo-pm/boost-config"
revision = "e60ff9d2778e3d2a6969859783a7c5bcc424f9a2"

[[lock]]
name = "github.com/buckaroo-pm/boost-detail"
revision = "95bd8a33609c6f6a276f3cff045cda0dfafe2b26"

[[lock]]
name = "github.com/buckaroo-pm/boost-type_traits"
revision = "19b9862c93b0796e346876782d217fbc33600c27"
